
# Use the official Python 3.8 slim image as the base image
FROM python:3.12-slim

# Set the working directory to /app
# WORKDIR /app
RUN apt update && pip install --upgrade pip
# Copy requirements.txt to the container and install dependencies
COPY ./ /src
RUN pip install mlflow pandas numpy pandas_datareader scikit-learn

