defaults:
  - _self_

role_name: server_role
assume_policy_document: |
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Principal": {
          "Service": "ec2.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
      }
    ]
  }
instance_profile_name: server_instance_profile
policy_names:
  - AmazonS3ReadOnlyAccess
  - AmazonEC2ContainerRegistryReadOnly
