# configs/aws/general.yaml
defaults:
  - userdata_script: demo
  - ingress_rules: 
    - ssh
  - _self_

username: ec2-user
instance_name: 'instance_2'
group_name: 'aws_template_1'
key_pair: 'aws_template_key'
image_id: 'ami-001843b876406202a'
instance_type: 't2.micro'
private_key_path: ""