image_id: 'ami-001843b876406202a'
instance_type: 't2.micro'
ingress_rules:
  - IpProtocol: 'tcp'
    FromPort: 22
    ToPort: 22
    IpRanges:
      - CidrIp: '0.0.0.0/0'  # Allow SSH from anywhere

userdata_script: |
  #!/bin/bash
  yum update -y
  yum install -y httpd
  systemctl start httpd
  systemctl enable httpd
  echo "<html><body><h1>Welcome to My Website</h1></body></html>" > /var/www/html/index.html
