FROM bitnami/mlflow:latest

COPY ./code /code
COPY ./code_config code_config
COPY ./.dvc ./data_dir.dvc 
# Set up a virtual environment and install dependencies
RUN python3 -m venv .venv && \
    .venv/bin/pip install -r /code/requirements.txt --no-cache-dir 

ENTRYPOINT [ "/.venv/bin/python3" ]