FROM bitnami/mlflow:latest

# Your remaining commands...
CMD mlflow server \
    --backend-store-uri sqlite:///$(pwd)/demo_sqlite_db/mlflow.db \
    --default-artifact-root file://$(pwd)/demo_artifact_store/ \
    --host 0.0.0.0 \
    --port 5000
