assume_policy_document:
  |
  {
  "Version": "2012-10-17",
  "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "ec2.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
  }

policy_names:
  - "AmazonS3ReadOnlyAccess"
  - "AmazonEC2ContainerRegistryReadOnly"